### ISSUE TITLE
Configuration described in documentation is not woking

### ISSUE THREAD

**Issue by psoares** [grails/gorm-cassandra#1]
I tried to setup a grails 3 (3.1.10) project with cassandra, as described in http://gorm.grails.org/latest/cassandra/manual/index.html, and tried to make it point to an external cassandra, located in a server which name is "dbhost". dbhost responds to ping in my terminal so I know it's a valid hostname. However, when I start the grails app, it keeps pointing to `localhost/127.0.0.1:9042` despite my config in application.yml being :

```
grails:
    profile: rest-api
    codegen:
        defaultPackage: com.test
    spring:
        transactionManagement:
            proxies: false
    cassandra:
        contactPoints: dbhost
        port: 9042
        keyspace:
            name: foo
```

Also, the documentation says 

> If you want to configure how Grails connects to Cassandra then you can do so using the following settings in grails-app/conf/application.yml:
> 
> ```
> grails:
>     cassandra:
>         contactPoints: localhost
>         port: 9042
>         keyspace:
>             name: foo
>     }
> }
> ```

I think the last 2 square brackets are not part of the yaml syntax.
